### ISSUE TITLE
关于采用pdf和zip的建议

### ISSUE THREAD

**Issue by YanB25** [sysuexam/SYSU-Exam#2]
建议文件采用pdf格式而非其他格式上传。  
毕竟大多数情况下都没有修改文件的需求，且pdf格式更友好  
可将repo里现存的文档转为pdf文件
建议压缩文档采用zip格式

**Comment by YanB25** [comment]
另，对于.png/.jpg格式的文件，整合到同一个pdf文件中？

**Comment by jskyzero** [comment]
我也有同样的想法，另外，关于具体试卷的年份是否需要再分一个文件夹？

**Comment by YanB25** [comment]
@jskyzero这点你可以再看一个issue讨论

**Comment by YanB25** [comment]
@jskyzero这点你可以再开一个issue讨论

**Comment by Zing22** [comment]
转换成PDF是个好主意，但doc文件比较容易编辑，可以同时保留
