### ISSUE TITLE
固体物理学试卷

### ISSUE THREAD

**Issue by ddddavid-he** [sysuexam/SYSU-Exam#20]
课程名称：
固体物理学
[固体物理期中测试-2020.pdf](https://github.com/sysuexam/SYSU-Exam/files/7457591/-2020.pdf)
[固体物理期中测试题--2017.pdf](https://github.com/sysuexam/SYSU-Exam/files/7457593/--2017.pdf)
[固体物理期中测试题--2018.pdf](https://github.com/sysuexam/SYSU-Exam/files/7457594/--2018.pdf)
[固体物理期中测试题--2019.pdf](https://github.com/sysuexam/SYSU-Exam/files/7457595/--2019.pdf)
[固体物理期中考试题（光信2016-2017学年）-答案.pdf](https://github.com/sysuexam/SYSU-Exam/files/7457596/2016-2017.-.pdf)

**Comment by ddddavid-he** [comment]
有一个文件命名错误  ：
固体物理期中测试-2020.pdf 
改成
固体物理期中测试-2016.pdf

**Comment by Zing22** [comment]
赞啊，晚点我整理下

**Comment by Zing22** [comment]
已上传
